### ISSUE TITLE
Feature Request: Add colour pattern image if there is course image available

### ISSUE THREAD

**Issue by michael-milette** [andurif/moodle-theme_bandeau#6]
I like the course image which appears next to the course name in the page heading. However, for courses that don't have a course image, it might be more consistent to display the colour pattern as seen when the courses are displayed in the dashboard.

Let me know if you have any questions.

Best regards,

Michael

**Comment by andurif** [comment]
Hello Michael,
Thanks for your suggestion and sorry for the very late answer.

In the newest version of the plugin I took your idea in consideration and add the use of the colour pattern for courses with no image defined and if there isn't a default image defined in the administration. 
Feel free to tell us if this is what you had in mind or if you have problems with this version.

Best regards,

Anthony
